{
 "title": "13 - Dashboard kaspersky Security Center",
 "description": "Material do Treinamento da 2MTI Treinamentos & Serviços.\n\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Grupos", "query": "*" },
   { "name": "Hosts", "query": "$Grupos.*" }
  ]
 },
 "panels": [
  {
   "title": "Logo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "content": "<center> <img src=\"https://victorh2007.files.wordpress.com/2013/04/kaspersky.png\" />"
    }
   ]
  },
  {
   "title": "Informacoes de update do kaspersky security center",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 7, "x": 0, "y": 2 } },
  {
   "title": "Status atualização da base de dados",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 7, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Update do Kaspersky Security Center"
     },
     "group": { "filter": "$Grupos" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Status atualização da base de dados do servidor"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ultimo update do servidor Kaspersky Security Center",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Update do Kaspersky Security Center"
     },
     "group": { "filter": "$Grupos" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Ultimo update do servidor Kaspersky Security Center"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Informações de hosts por status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quantidade de Eventos Criticos!",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": {
        "filter": "Informacoes de Protecao do Kaspersky Security Center"
       },
       "group": { "filter": "$Grupos" },
       "host": { "filter": "$Hosts" },
       "item": {
        "filter": "Quantidade de Eventos Criticos nao tratados"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Quantidade de Host com vírus!",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": {
        "filter": "Informacoes de Protecao do Kaspersky Security Center"
       },
       "group": { "filter": "$Grupos" },
       "host": { "filter": "$Hosts" },
       "item": {
        "filter": "Quantidade de Host com vírus ou arquivos nao processados"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Quantidade de Hosts não verificados!",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": {
        "filter": "Informacoes de Protecao do Kaspersky Security Center"
       },
       "group": { "filter": "$Grupos" },
       "host": { "filter": "$Hosts" },
       "item": {
        "filter": "Quantidade de Hosts não verificados em 7 dias"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "hosts sem executar o antivírus!",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": {
        "filter": "Informacoes de Protecao do Kaspersky Security Center"
       },
       "group": { "filter": "$Grupos" },
       "host": { "filter": "$Hosts" },
       "item": {
        "filter": "Quantidade de hosts sem executar o antivírus em 7 dias"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  { "title": "Informações do sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Quantidade de host com Antivirus!",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes do Sistema do Kaspersky Security Center"
     },
     "group": { "filter": "$Grupos" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Quantidade de host com Antivirus no Kaspersky Security Center"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Quantidade de host no console!",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes do Sistema do Kaspersky Security Center"
     },
     "group": { "filter": "$Grupos" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Quantidade de host no console do Kaspersky Security Center"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status da rede logica do Servidor!",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes do Sistema do Kaspersky Security Center"
     },
     "group": { "filter": "$Grupos" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Status da rede logica do Servidor de Administracao"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status do subsistema de eventos!",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes do Sistema do Kaspersky Security Center"
     },
     "group": { "filter": "$Grupos" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Status do subsistema de eventos"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}