{
 "title": "SITES TECNOLOGIA 2",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API Customer",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API Customer\" of scenario \"API Customer\"."
     },
     "itemTag": { "filter": "API Customer" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API Fiscal",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API Fiscal\" of scenario \"API Fiscal\"."
     },
     "itemTag": { "filter": "API Fiscal" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API Leads",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API Leads\" of scenario \"API Leads\"."
     },
     "itemTag": { "filter": "API Leads" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Instituto EP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Instituto EP\" of scenario \"Instituto EP\"."
     },
     "itemTag": { "filter": "Instituto EP" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "OA Eventos",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"OA Eventos\" of scenario \"OA Eventos\"."
     },
     "itemTag": { "filter": "OA Eventos" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API PreSalesOrder",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API PreSalesOrder\" of scenario \"API PreSalesOrder\"."
     },
     "itemTag": { "filter": "API PreSalesOrder" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Agenda Barretos",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Agenda Barretos\" of scenario \"Agenda Barretos\"."
     },
     "itemTag": { "filter": "Agenda Barretos" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Agenda Rio Claro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Agenda Rio Claro\" of scenario \"Agenda Rio Claro\"."
     },
     "itemTag": { "filter": "Agenda Rio Claro" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Agenda São Carlos",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Agenda São Carlos\" of scenario \"Agenda São Carlos\"."
     },
     "itemTag": { "filter": "Agenda São Carlos" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Agenda Araraquara",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Agenda Araraquara\" of scenario \"Agenda Araraquara\"."
     },
     "itemTag": { "filter": "Agenda Araraquara" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CBN Campinas",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"CBN Campinas\" of scenario \"CBN Campinas\"."
     },
     "itemTag": { "filter": "CBN Campinas" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Conexão Solidária",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Conexão Solidária\" of scenario \"Conexão Solidária\"."
     },
     "itemTag": { "filter": "Conexão Solidária" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ester Agroindustrial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Ester Agroindustrial\" of scenario \"Ester Agroindustrial\"."
     },
     "itemTag": { "filter": "Ester Agroindustrial" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CBN São Carlos",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"CBN São Carlos\" of scenario \"CBN São Carlos\"."
     },
     "itemTag": { "filter": "CBN São Carlos" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Intranet04",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Intranet04\" of scenario \"Intranet04\"."
     },
     "itemTag": { "filter": "Intranet04" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "EP FM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"EP FM\" of scenario \"EP FM\"."
     },
     "itemTag": { "filter": "EP FM" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Motor do Futuro",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Motor do Futuro\" of scenario \"Motor do Futuro\"."
     },
     "itemTag": { "filter": "Motor do Futuro" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Projetos Empresas Pioneiras",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Projetos Empresas Pioneiras\" of scenario \"Projetos Empresas Pioneiras\"."
     },
     "itemTag": { "filter": "Projetos Empresas Pioneiras" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Agenda Campinas",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Agenda Campinas\" of scenario \"Agenda Campinas\"."
     },
     "itemTag": { "filter": "Agenda Campinas" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CBN Araraquara",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"CBN Araraquara\" of scenario \"CBN Araraquara\"."
     },
     "itemTag": { "filter": "CBN Araraquara" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Intranet02",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Intranet02\" of scenario \"Intranet02\"."
     },
     "itemTag": { "filter": "Intranet02" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redirect Campanha Aedes Aegypti (protocolo HTTP)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Redirect Campanha Aedes Aegypti (protocolo HTTP)\" of scenario \"Redirect Campanha Aedes Aegypti (protocolo HTTP)\"."
     },
     "itemTag": {
      "filter": "Redirect Campanha Aedes Aegypti (protocolo HTTP)"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Empresas Pioneiras",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Empresas Pioneiras\" of scenario \"Empresas Pioneiras\"."
     },
     "itemTag": { "filter": "Empresas Pioneiras" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redirect FUTSAL (protocolo HTTP)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Redirect FUTSAL (protocolo HTTP)\" of scenario \"Redirect FUTSAL (protocolo HTTP)\"."
     },
     "itemTag": {
      "filter": "Redirect FUTSAL (protocolo HTTP)"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redirect Campanha do Agasalho (protocolo HTTP)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Redirect Campanha do Agasalho (protocolo HTTP)\" of scenario \"Redirect Campanha do Agasalho (protocolo HTTP)\"."
     },
     "itemTag": {
      "filter": "Redirect Campanha do Agasalho (protocolo HTTP)"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Agenda Franca",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Agenda Franca\" of scenario \"Agenda Franca\"."
     },
     "itemTag": { "filter": "Agenda Franca" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Player EP FM Campinas",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Player EP FM Campinas\" of scenario \"Player EP FM Campinas\"."
     },
     "itemTag": { "filter": "Player EP FM Campinas" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Player EP FM Araraquara",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Player EP FM Araraquara\" of scenario \"Player EP FM Araraquara\"."
     },
     "itemTag": { "filter": "Player EP FM Araraquara" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tudo EP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Tudo EP\" of scenario \"Tudo EP\"."
     },
     "itemTag": { "filter": "Tudo EP" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API SysAdmin",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API SysAdmin\" of scenario \"API SysAdmin\"."
     },
     "itemTag": { "filter": "API SysAdmin" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CBN Campinas Player",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"CBN Campinas Player\" of scenario \"CBN Campinas Player\"."
     },
     "itemTag": { "filter": "CBN Campinas Player" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Virando Bixo",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Virando Bixo\" of scenario \"Virando Bixo\"."
     },
     "itemTag": { "filter": "Virando Bixo" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Player EP FM Sao Carlos",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Player EP FM Sao Carlos\" of scenario \"Player EP FM Sao Carlos\"."
     },
     "itemTag": { "filter": "Player EP FM Sao Carlos" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API Financial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API Financial\" of scenario \"API Financial\"."
     },
     "itemTag": { "filter": "API Financial" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API Ticket",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API Ticket\" of scenario \"API Ticket\"."
     },
     "itemTag": { "filter": "API Ticket" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Negócios Empresas Pioneiras",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Negócios Empresas Pioneiras\" of scenario \"Negócios Empresas Pioneiras\"."
     },
     "itemTag": { "filter": "Negócios Empresas Pioneiras" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redirect Corrida Integracao (protocolo HTTP)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Redirect Corrida Integracao (protocolo HTTP)\" of scenario \"Redirect Corrida Integracao (protocolo HTTP)\"."
     },
     "itemTag": {
      "filter": "Redirect Corrida Integracao (protocolo HTTP)"
     },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Institucional EPTV",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Institucional EPTV\" of scenario \"Institucional EPTV\"."
     },
     "itemTag": { "filter": "Institucional EPTV" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Intranet01",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Intranet01\" of scenario \"Intranet01\"."
     },
     "itemTag": { "filter": "Intranet01" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ta Combinado",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Ta Combinado\" of scenario \"Ta Combinado\"."
     },
     "itemTag": { "filter": "Ta Combinado" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API Customized",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API Customized\" of scenario \"API Customized\"."
     },
     "itemTag": { "filter": "API Customized" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API Products",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API Products\" of scenario \"API Products\"."
     },
     "itemTag": { "filter": "API Products" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API Contacts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API Contacts\" of scenario \"API Contacts\"."
     },
     "itemTag": { "filter": "API Contacts" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Intranet03",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Intranet03\" of scenario \"Intranet03\"."
     },
     "itemTag": { "filter": "Intranet03" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API Content",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API Content\" of scenario \"API Content\"."
     },
     "itemTag": { "filter": "API Content" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Agenda Piracicaba",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Agenda Piracicaba\" of scenario \"Agenda Piracicaba\"."
     },
     "itemTag": { "filter": "Agenda Piracicaba" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CBN Ribeirão",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"CBN Ribeirão\" of scenario \"CBN Ribeirão\"."
     },
     "itemTag": { "filter": "CBN Ribeirão" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API Sales",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API Sales\" of scenario \"API Sales\"."
     },
     "itemTag": { "filter": "API Sales" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ribeirão Motofestival",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Ribeirão Motofestival\" of scenario \"Ribeirão Motofestival\"."
     },
     "itemTag": { "filter": "Ribeirão Motofestival" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "EPTickets",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"EPTicekts\" of scenario \"EPTicekts\"."
     },
     "itemTag": { "filter": "EPTicekts" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Agenda Limeira",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Agenda Limeira\" of scenario \"Agenda Limeira\"."
     },
     "itemTag": { "filter": "Agenda Limeira" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Agenda Agronegocio",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Agenda Agronegocio\" of scenario \"Agenda Agronegocio\"."
     },
     "itemTag": { "filter": "Agenda Agronegocio" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CBN Ribeirão Noticia Interna",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"CBN Ribeirão Noticia Interna\" of scenario \"CBN Ribeirão Noticia Interna\"."
     },
     "itemTag": { "filter": "CBN Ribeirão Noticia Interna" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CBN Ribeirão Preto Player",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"CBN Ribeirão Preto Player\" of scenario \"CBN Ribeirão Preto Player\"."
     },
     "itemTag": { "filter": "CBN Ribeirão Preto Player" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Dialogos na educação",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Dialogosnaeducacao\" of scenario \"Dialogosnaeducacao\"."
     },
     "itemTag": { "filter": "Dialogosnaeducacao" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "EP Radio",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"EP Radio\" of scenario \"EP Radio\"."
     },
     "itemTag": { "filter": "EP Radio" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cidade On WP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"Cidade On WP\" of scenario \"Cidade On WP\"."
     },
     "itemTag": { "filter": "Cidade On WP" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "API Reports",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "TECNOLOGIA" },
     "host": { "filter": "SITES - TECNOLOGIA" },
     "item": {
      "filter": "Response code for step \"API Reports\" of scenario \"API Reports\"."
     },
     "itemTag": { "filter": "API Reports" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}